### ISSUE TITLE
didn't see some courses in the list

### ISSUE THREAD

**Issue by ppa1985** [debakarr/kodekloud-downloader#12]
I didn't see following courses in the course list

Lens- Kubernetes IDE
Linode- Kubernetes Engine

**Comment by debakarr** [comment]
Currently it only parses the course from this link: https://kodekloud.com/courses/

If you open this in Incognito, you will see that the courses listed are part of this.

Looks like the courses you mentioned is part of Bonus courses and are not part of regular course. Still you can download by passing the course link to the cli tool.

**Comment by debakarr** [comment]
Can be now downloaded via url
