### ISSUE TITLE
Cka Course enrolled download the same video for all chapters

### ISSUE THREAD

**Issue by davideperson** [debakarr/kodekloud-downloader#13]
![image](https://user-images.githubusercontent.com/58345409/234725008-1c1f6488-71c5-42e8-840f-ecef4b2ffbd1.png)

**Comment by blebleblee** [comment]
This is happening randomly in other courses as well. Cookies are fresh and in the background I have the session running.

**Comment by davideperson** [comment]
> This is happening randomly in other courses as well. Cookies are fresh and in the background I have the session running.

how did  you download the course?

can you explain your steps?

**Comment by davideperson** [comment]
> Nothing special `kodekloud dl -o /data -c ~/kodekloud.com_cookies.txt $url`
> 
> However, I realized the course with this problem changed. Now I had a button to enroll. I'm sure I enrolled before. So it must be something on KodeKloud side

i fixed  adding full path of url course at the end

**Comment by debakarr** [comment]
I don't think this issue should be there anymore. I added an additional check to stop the download if same video is getting downloaded.

**Comment by zainulhasan** [comment]
I face the same issue. I downloaded all the courses took 2 days and at the end. names of the files are different but all the videos are the intro of the video.
