### ISSUE TITLE
Is there option for download all availabe courses.

### ISSUE THREAD

**Issue by zainulhasan** [debakarr/kodekloud-downloader#14]

**Comment by performautodev** [comment]
yes


kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/12-factor-app/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/advanced-golang/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/amazon-elastic-container-service-aws-ecs/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ansible-advanced-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/argocd/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/aws-lambda/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/az-104-microsoft-azure-administrator/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;az-305_microsoft-azure-solutions-architect-expert/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;certified-kubernetes-application-developer-ckad/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;certified-kubernetes-security-specialist-cks/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;python-entry-level-programmer-certification/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/chef-for-the-absolute-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/certified-kubernetes-administrator-cka/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/cks-challenges/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/devops-interview-prep-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/devops-pre-requisite-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/devsecops/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/docker-swarm-services-stacks-hands-on/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/docker-certified-associate-exam-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/docker-for-the-absolute-beginner/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/gcp-cloud-digital-leader-certification/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/gcp-devops-project/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/git-for-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/golang/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/terraform-cloud/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;hashicorp-certified-consul-associate-certification/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;hashicorp-certified-vault-associate-certification/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;hashicorp-certified-vault-operations-professional-2022/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/helm-for-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/istio-service-mesh/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/jenkins/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/json-path-quiz/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/kubernetes-challenges/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;kubernetes-for-the-absolute-beginners-hands-on/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/kustomize/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;ansible-for-the-absolute-beginners-course/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/the-linux-basics-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/linux-challenges/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;linux-foundation-certified-system-administrator-lfcs/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;linux-professional-institute-lpic-1-exam-101/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/open-source/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/openshift-for-the-absolute-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/openshift-4/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;certified-associate-in-python-programming/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/prometheus-certified-associate-pca/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/puppet-for-the-absolute-beginners-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;red-hat-certified-system-administratorrhcsa-2/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/shell-scripts-for-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/hashicorp-certified-terraform-associate/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/terraform-for-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/terraform-challenges/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;ultimate-certified-kubernetes-administrator-cka-mock-exam/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ ;ultimate-certified-kubernetes-application-developer-ckad-mock-exam-series/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/jinja2-templating/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/linode-kubernetes-engine/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/lens-introduction/ ;

**Comment by zainulhasan** [comment]
There were a few issues I fixed it.
Thanks
```
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/12-factor-app/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/advanced-golang/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/amazon-elastic-container-service-aws-ecs/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ansible-advanced-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/argocd/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/aws-lambda/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/az-104-microsoft-azure-administrator/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/az-305_microsoft-azure-solutions-architect-expert/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/certified-kubernetes-application-developer-ckad/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/certified-kubernetes-security-specialist-cks/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/python-entry-level-programmer-certification/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/chef-for-the-absolute-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/certified-kubernetes-administrator-cka/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/cks-challenges/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/devops-interview-prep-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/devops-pre-requisite-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/devsecops/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/docker-swarm-services-stacks-hands-on/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/docker-certified-associate-exam-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/docker-for-the-absolute-beginner/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/gcp-cloud-digital-leader-certification/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/gcp-devops-project/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/git-for-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/golang/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/terraform-cloud/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/hashicorp-certified-consul-associate-certification/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/hashicorp-certified-vault-associate-certification/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/hashicorp-certified-vault-operations-professional-2022/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/helm-for-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/istio-service-mesh/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/jenkins/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/json-path-quiz/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/kubernetes-challenges/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/kubernetes-for-the-absolute-beginners-hands-on/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/kustomize/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ansible-for-the-absolute-beginners-course/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/the-linux-basics-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/linux-challenges/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/linux-foundation-certified-system-administrator-lfcs/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/linux-professional-institute-lpic-1-exam-101/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/open-source/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/openshift-for-the-absolute-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/openshift-4/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/certified-associate-in-python-programming/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/prometheus-certified-associate-pca/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/puppet-for-the-absolute-beginners-course/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/red-hat-certified-system-administratorrhcsa-2/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/shell-scripts-for-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/hashicorp-certified-terraform-associate/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/terraform-for-beginners/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/terraform-challenges/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ultimate-certified-kubernetes-administrator-cka-mock-exam/;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/ultimate-certified-kubernetes-application-developer-ckad-mock-exam-series/
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/jinja2-templating/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/linode-kubernetes-engine/ ;
kodekloud dl -o . -c cookie.txt -q 1080p https://kodekloud.com/courses/lens-introduction/ ;
```

**Comment by SJ50** [comment]
wrote a small script
````
#!/bin/bash

COOKIE=$2
QUALITY="1080p"
OUTPUT=$1

# List of URLs
URLS=(
    "https://kodekloud.com/courses/12-factor-app/"
    "https://kodekloud.com/courses/advanced-golang/"
    "https://kodekloud.com/courses/amazon-elastic-container-service-aws-ecs/"
    "https://kodekloud.com/courses/ansible-advanced-course/"
    "https://kodekloud.com/courses/argocd/"
    "https://kodekloud.com/courses/aws-lambda/"
    "https://kodekloud.com/courses/az-104-microsoft-azure-administrator/"
    "https://kodekloud.com/courses/az-305_microsoft-azure-solutions-architect-expert/"
    "https://kodekloud.com/courses/certified-kubernetes-application-developer-ckad/"
    "https://kodekloud.com/courses/certified-kubernetes-security-specialist-cks/"
    "https://kodekloud.com/courses/python-entry-level-programmer-certification/"
    "https://kodekloud.com/courses/chef-for-the-absolute-beginners/"
    "https://kodekloud.com/courses/certified-kubernetes-administrator-cka/"
    "https://kodekloud.com/courses/cks-challenges/"
    "https://kodekloud.com/courses/devops-interview-prep-course/"
    "https://kodekloud.com/courses/devops-pre-requisite-course/"
    "https://kodekloud.com/courses/devsecops/"
    "https://kodekloud.com/courses/docker-swarm-services-stacks-hands-on/"
    "https://kodekloud.com/courses/docker-certified-associate-exam-course/"
    "https://kodekloud.com/courses/docker-for-the-absolute-beginner/"
    "https://kodekloud.com/courses/gcp-cloud-digital-leader-certification/"
    "https://kodekloud.com/courses/gcp-devops-project/"
    "https://kodekloud.com/courses/git-for-beginners/"
    "https://kodekloud.com/courses/golang/"
    "https://kodekloud.com/courses/terraform-cloud/"
    "https://kodekloud.com/courses/hashicorp-certified-consul-associate-certification/"
    "https://kodekloud.com/courses/hashicorp-certified-vault-associate-certification/"
    "https://kodekloud.com/courses/hashicorp-certified-vault-operations-professional-2022/"
    "https://kodekloud.com/courses/helm-for-beginners/"
    "https://kodekloud.com/courses/istio-service-mesh/"
    "https://kodekloud.com/courses/jenkins/"
    "https://kodekloud.com/courses/json-path-quiz/"
    "https://kodekloud.com/courses/kubernetes-challenges/"
    "https://kodekloud.com/courses/kubernetes-for-the-absolute-beginners-hands-on/"
    "https://kodekloud.com/courses/kustomize/"
)

# Loop through URLs and download the files
for url in "${URLS[@]}"; do
    kodekloud dl -o "$OUTPUT" -c "$COOKIE" -q "$QUALITY" "$url"
done
````

save above as `all_course_downloader.sh` and run as follow
````
bash all_course_downloader.sh /download/location /cookie/location/cookie.txt
````

**Comment by debakarr** [comment]
latest version let you select the range.

like 1-3,6-8,10-13,40-44,55 will download the courses in [1, 2, 3, 6, 7, 8, 10, 11, 12, 13, 40, 41, 42, 43, 44, 55]
