### ISSUE TITLE
i am facing this issue 

### ISSUE THREAD

**Issue by Omaratef215** [debakarr/kodekloud-downloader#18]
It starts downloading then this error shows up:
"Your cookie might have expired or you don't have access to the course" 
 
Even though I have enrolled the course and followed the cookie instruction

**Comment by debakarr** [comment]
Free week has ended. Do you still have access to the course?

**Comment by Omaratef215** [comment]
yes I do ,
 I've bought it :>

**Comment by YoungsoonLee** [comment]
Same issue.
I've paid and bought it. but I got same error.

**Comment by debakarr** [comment]
Please check access and if it is there then enroll in the course and then download the cookie..
Downloading cookie before enrolling may not work.
