### ISSUE TITLE
Course not downloading | Getting error related to cookie

### ISSUE THREAD

**Issue by fahimsayed1985** [debakarr/kodekloud-downloader#20]
I am getting below errors while executing command - kodekloud dl -o . -c /cookie.txt
![cookie error](https://github.com/debakarr/kodekloud-downloader/assets/115891846/cb06cb7f-91c4-4d3c-8d0c-717619aa6f96)

Your cookie might have expired or you don't have access to the course.
Please refresh/regenerate the cookie or enroll in the course and try again.

**Comment by debakarr** [comment]
Hey. I don't have the premium now. 25th September again there's going to be a free week. I can try and let you know by then.

**Comment by umerpaknamal** [comment]
Facing same issue ,yeah 25th of september there is a free weak please fix this thanks

**Comment by debakarr** [comment]
Hi, make sure you have access to the course and have enrolled in the course before downloading the cookie.
Will be closing this. Reopen if issue persist.
