### ISSUE TITLE
A fix if download stopped in middle

### ISSUE THREAD

**Issue by hypercleric** [debakarr/kodekloud-downloader#24]
yt_dlp.networking.exceptions.RequestError: SSLV3_ALERT_HANDSHAKE_FAILURE: The server may not support the current cipher list. Try using --legacy-server-connect

if this is the case just redownload that it will continue (try to download the courses one by one )  use this command 

kodekloud dl -o . -c /path/to/cookie.txt  

if it stops just  re-download by choosing the number of the course , you can try this multiple  times  also dont worry it will show the part which is already downloades as already downloaded in the cli.

Hope This helps (:👍🏻 

Also very thanks to debakar

**Comment by debakarr** [comment]
Thanks for this.
