### ISSUE TITLE
ERROR: Failed building wheel for validators

### ISSUE THREAD

**Issue by HamadaRh** [debakarr/kodekloud-downloader#28]
Hello,
I have python3.8
and till now can't pip install -U kodekloud-downloader , always get 
ERROR: Failed building wheel for validators

screen https://prnt.sc/kKo0R-o_puj3

`error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]`

`oduleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for validators
  Running setup.py clean for validators
Failed to build validators
ERROR: Could not build wheels for validators, which is required to install pyproject.toml-based projects`

`# pip freeze
attrs==23.1.0
Brotli==1.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.5
idna==3.4
importlib-resources==6.1.0
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
mutagen==1.47.0
pep517==0.13.0
pkgutil_resolve_name==1.3.10
pycryptodomex==3.19.0
pyproject-toml==0.0.10
python-dotenv==1.0.0
referencing==0.30.2
requests==2.31.0
rpds-py==0.10.3
toml==0.10.2
tomli==2.0.1
urllib3==2.0.5
validators==0.22.0
websockets==11.0.3
yt-dlp==2023.9.24
zipp==3.17.0`

please help me to complete install and down one course
sorry as i'm not full familar with python

**Comment by debakarr** [comment]
I would suggest trying upgrading the pip.
