### ISSUE TITLE
cookies expire 

### ISSUE THREAD

**Issue by Gaser98** [debakarr/kodekloud-downloader#29]
cookies expire too fast and it fails to load courses

**Comment by debakarr** [comment]
Can you also attach the course url and the output log.

**Comment by deepakkumar07-debug** [comment]
I'm also facing same problem
course: https://kodekloud.com/courses/mastering-generative-ai-with-open-ai/

output log

2023-09-29 04:56:18,484 - INFO - Writing video file... KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/1 - Introduction to Course 0216...
2023-09-29 04:56:18,484 - INFO - Parsing url: https://kodekloud.com/topic/introduction-to-course/
[generic] Extracting URL: https://kodekloud.com/topic/introduction-to-course/
[generic] introduction-to-course: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] introduction-to-course: Extracting information
[vimeo] Extracting URL: https://player.vimeo.com/video/863869112?dnt=1&app_id=122963&controls=1&autoplay=1&muted=1&api=1#...o-course%2F%22%7D%7D
[vimeo] 863869112: Downloading webpage
[vimeo] 863869112: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863869112: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863869112: Downloading fastly_skyfire m3u8 information
[vimeo] 863869112: Downloading fastly_skyfire m3u8 information
[vimeo] 863869112: Downloading google_mediacdn m3u8 information
[vimeo] 863869112: Downloading google_mediacdn m3u8 information
[vimeo] 863869112: Downloading akfire_interconnect_quic MPD information
[vimeo] 863869112: Downloading akfire_interconnect_quic MPD information
[vimeo] 863869112: Downloading fastly_skyfire MPD information
[vimeo] 863869112: Downloading fastly_skyfire MPD information
[vimeo] 863869112: Downloading google_mediacdn MPD information
[vimeo] 863869112: Downloading google_mediacdn MPD information
[info] 863869112: Downloading subtitles: en-x-autogen
[info] 863869112: Downloading 1 format(s): dash-google_mediacdn_sep-video-e056fb4f+dash-google_mediacdn_sep-audio-ad7e10eb
[info] Writing video subtitles to: KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/1 - Introduction to Course 0216.en-x-autogen.vtt
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/1 - Introduction to Course 0216.en-x-autogen.vtt
[download] 100% of    3.11KiB in 00:00:00 at 7.58KiB/s
[dashsegments] Total fragments: 24
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/1 - Introduction to Course 0216.fdash-google_mediacdn_sep-video-e056fb4f.mp4
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of   34.97MiB in 00:00:05 at 6.43MiB/s
[dashsegments] Total fragments: 24
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/1 - Introduction to Course 0216.fdash-google_mediacdn_sep-audio-ad7e10eb.m4a
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of    1.66MiB in 00:00:00 at 2.57MiB/s
[Merger] Merging formats into "KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/1 - Introduction to Course 0216.mkv"
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/1 - Introduction to Course 0216.fdash-google_mediacdn_sep-video-e056fb4f.mp4 (pass -k to keep)
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/1 - Introduction to Course 0216.fdash-google_mediacdn_sep-audio-ad7e10eb.m4a (pass -k to keep)
2023-09-29 04:56:33,550 - INFO - Writing resource file... KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/2 - Join Our Community...
2023-09-29 04:56:33,976 - INFO - Writing resource file... KodeKloud/Mastering Generative AI with OpenAI/1 - Introduction/3 - Important Note to Students...
2023-09-29 04:56:35,645 - INFO - Writing video file... KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/1 - Section Introduction 0044...
2023-09-29 04:56:35,645 - INFO - Parsing url: https://kodekloud.com/topic/section-introduction-33/
[generic] Extracting URL: https://kodekloud.com/topic/section-introduction-33/
[generic] section-introduction-33: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] section-introduction-33: Extracting information
[vimeo] Extracting URL: https://player.vimeo.com/video/863908925?dnt=1&app_id=122963&controls=1&autoplay=1&muted=1&api=1#...ction-33%2F%22%7D%7D
[vimeo] 863908925: Downloading webpage
[vimeo] 863908925: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863908925: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863908925: Downloading fastly_skyfire m3u8 information
[vimeo] 863908925: Downloading fastly_skyfire m3u8 information
[vimeo] 863908925: Downloading google_mediacdn m3u8 information
[vimeo] 863908925: Downloading google_mediacdn m3u8 information
[vimeo] 863908925: Downloading akfire_interconnect_quic MPD information
[vimeo] 863908925: Downloading akfire_interconnect_quic MPD information
[vimeo] 863908925: Downloading fastly_skyfire MPD information
[vimeo] 863908925: Downloading fastly_skyfire MPD information
[vimeo] 863908925: Downloading google_mediacdn MPD information
[vimeo] 863908925: Downloading google_mediacdn MPD information
[info] 863908925: Downloading subtitles: en-x-autogen
[info] 863908925: Downloading 1 format(s): hls-google_mediacdn_sep-414+dash-google_mediacdn_sep-audio-13c7b207
[info] Writing video subtitles to: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/1 - Section Introduction 0044.en-x-autogen.vtt
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/1 - Section Introduction 0044.en-x-autogen.vtt
[download] 100% of    1.20KiB in 00:00:00 at 3.29KiB/s
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 8
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/1 - Section Introduction 0044.fhls-google_mediacdn_sep-414.mp4
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of    1.39MiB in 00:00:00 at 4.56MiB/s
[dashsegments] Total fragments: 9
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/1 - Section Introduction 0044.fdash-google_mediacdn_sep-audio-13c7b207.m4a
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of  553.12KiB in 00:00:00 at 1.68MiB/s
[Merger] Merging formats into "KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/1 - Section Introduction 0044.mkv"
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/1 - Section Introduction 0044.fdash-google_mediacdn_sep-audio-13c7b207.m4a (pass -k to keep)
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/1 - Section Introduction 0044.fhls-google_mediacdn_sep-414.mp4 (pass -k to keep)
2023-09-29 04:56:46,954 - INFO - Writing video file... KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/2 - Introduction to AI 0456...
2023-09-29 04:56:46,954 - INFO - Parsing url: https://kodekloud.com/topic/introduction-to-ai/
[generic] Extracting URL: https://kodekloud.com/topic/introduction-to-ai/
[generic] introduction-to-ai: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] introduction-to-ai: Extracting information
[vimeo] Extracting URL: https://player.vimeo.com/video/863908833?dnt=1&app_id=122963&controls=1&autoplay=1&muted=1&api=1#...on-to-ai%2F%22%7D%7D
[vimeo] 863908833: Downloading webpage
[vimeo] 863908833: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863908833: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863908833: Downloading fastly_skyfire m3u8 information
[vimeo] 863908833: Downloading fastly_skyfire m3u8 information
[vimeo] 863908833: Downloading google_mediacdn m3u8 information
[vimeo] 863908833: Downloading google_mediacdn m3u8 information
[vimeo] 863908833: Downloading akfire_interconnect_quic MPD information
[vimeo] 863908833: Downloading akfire_interconnect_quic MPD information
[vimeo] 863908833: Downloading fastly_skyfire MPD information
[vimeo] 863908833: Downloading fastly_skyfire MPD information
[vimeo] 863908833: Downloading google_mediacdn MPD information
[vimeo] 863908833: Downloading google_mediacdn MPD information
[info] 863908833: Downloading subtitles: en-x-autogen
[info] 863908833: Downloading 1 format(s): hls-google_mediacdn_sep-386+dash-google_mediacdn_sep-audio-0e33d10b
[info] Writing video subtitles to: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/2 - Introduction to AI 0456.en-x-autogen.vtt
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/2 - Introduction to AI 0456.en-x-autogen.vtt
[download] 100% of    6.90KiB in 00:00:00 at 17.36KiB/s
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 49
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/2 - Introduction to AI 0456.fhls-google_mediacdn_sep-386.mp4
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of    7.83MiB in 00:00:01 at 4.31MiB/s
[dashsegments] Total fragments: 51
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/2 - Introduction to AI 0456.fdash-google_mediacdn_sep-audio-0e33d10b.m4a
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of    3.59MiB in 00:00:00 at 4.13MiB/s
[Merger] Merging formats into "KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/2 - Introduction to AI 0456.mkv"
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/2 - Introduction to AI 0456.fdash-google_mediacdn_sep-audio-0e33d10b.m4a (pass -k to keep)
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/2 - Introduction to AI 0456.fhls-google_mediacdn_sep-386.mp4 (pass -k to keep)
2023-09-29 04:57:01,199 - INFO - Writing video file... KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/3 - Introduction to Generative AI 0254...
2023-09-29 04:57:01,199 - INFO - Parsing url: https://kodekloud.com/topic/introduction-to-generative-ai/
[generic] Extracting URL: https://kodekloud.com/topic/introduction-to-generative-ai/
[generic] introduction-to-generative-ai: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] introduction-to-generative-ai: Extracting information
[vimeo] Extracting URL: https://player.vimeo.com/video/863909046?dnt=1&app_id=122963&controls=1&autoplay=1&muted=1&api=1#...ative-ai%2F%22%7D%7D
[vimeo] 863909046: Downloading webpage
[vimeo] 863909046: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863909046: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863909046: Downloading fastly_skyfire m3u8 information
[vimeo] 863909046: Downloading fastly_skyfire m3u8 information
[vimeo] 863909046: Downloading google_mediacdn m3u8 information
[vimeo] 863909046: Downloading google_mediacdn m3u8 information
[vimeo] 863909046: Downloading akfire_interconnect_quic MPD information
[vimeo] 863909046: Downloading akfire_interconnect_quic MPD information
[vimeo] 863909046: Downloading fastly_skyfire MPD information
[vimeo] 863909046: Downloading fastly_skyfire MPD information
[vimeo] 863909046: Downloading google_mediacdn MPD information
[vimeo] 863909046: Downloading google_mediacdn MPD information
[info] 863909046: Downloading 1 format(s): hls-google_mediacdn_sep-414+dash-google_mediacdn_sep-audio-dc1ef55d
[info] There are no subtitles for the requested languages
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 29
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/3 - Introduction to Generative AI 0254.fhls-google_mediacdn_sep-414.mp4
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of    5.21MiB in 00:00:00 at 5.68MiB/s
[dashsegments] Total fragments: 30
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/3 - Introduction to Generative AI 0254.fdash-google_mediacdn_sep-audio-dc1ef55d.m4a
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of    2.11MiB in 00:00:00 at 3.65MiB/s
[Merger] Merging formats into "KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/3 - Introduction to Generative AI 0254.mkv"
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/3 - Introduction to Generative AI 0254.fhls-google_mediacdn_sep-414.mp4 (pass -k to keep)
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/3 - Introduction to Generative AI 0254.fdash-google_mediacdn_sep-audio-dc1ef55d.m4a (pass -k to keep)
2023-09-29 04:57:12,491 - INFO - Writing video file... KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/4 - Foundation Models 0237...
2023-09-29 04:57:12,491 - INFO - Parsing url: https://kodekloud.com/topic/foundation-models/
[generic] Extracting URL: https://kodekloud.com/topic/foundation-models/
[generic] foundation-models: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] foundation-models: Extracting information
[vimeo] Extracting URL: https://player.vimeo.com/video/863908881?dnt=1&app_id=122963&controls=1&autoplay=1&muted=1&api=1#...n-models%2F%22%7D%7D
[vimeo] 863908881: Downloading webpage
[vimeo] 863908881: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863908881: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 863908881: Downloading fastly_skyfire m3u8 information
[vimeo] 863908881: Downloading fastly_skyfire m3u8 information
[vimeo] 863908881: Downloading google_mediacdn m3u8 information
[vimeo] 863908881: Downloading google_mediacdn m3u8 information
[vimeo] 863908881: Downloading akfire_interconnect_quic MPD information
[vimeo] 863908881: Downloading akfire_interconnect_quic MPD information
[vimeo] 863908881: Downloading fastly_skyfire MPD information
[vimeo] 863908881: Downloading fastly_skyfire MPD information
[vimeo] 863908881: Downloading google_mediacdn MPD information
[vimeo] 863908881: Downloading google_mediacdn MPD information
[info] 863908881: Downloading subtitles: en-x-autogen
[info] 863908881: Downloading 1 format(s): hls-google_mediacdn_sep-356+dash-google_mediacdn_sep-audio-4a846989
[info] Writing video subtitles to: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/4 - Foundation Models 0237.en-x-autogen.vtt
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/4 - Foundation Models 0237.en-x-autogen.vtt
[download] 100% of    3.63KiB in 00:00:00 at 8.85KiB/s
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 26
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/4 - Foundation Models 0237.fhls-google_mediacdn_sep-356.mp4
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of    3.57MiB in 00:00:00 at 5.20MiB/s
[dashsegments] Total fragments: 27
[download] Destination: KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/4 - Foundation Models 0237.fdash-google_mediacdn_sep-audio-4a846989.m4a
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of    1.90MiB in 00:00:00 at 3.37MiB/s
[Merger] Merging formats into "KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/4 - Foundation Models 0237.mkv"
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/4 - Foundation Models 0237.fdash-google_mediacdn_sep-audio-4a846989.m4a (pass -k to keep)
Deleting original file KodeKloud/Mastering Generative AI with OpenAI/2 - What is Generative AI/4 - Foundation Models 0237.fhls-google_mediacdn_sep-356.mp4 (pass -k to keep)
Your cookie might have expired or you don't have access to the course.
Please refresh/regenerate the cookie or enroll in the course and try again.

**Comment by Tanis74** [comment]
I couldn't download the course during the free week. I have now bought a subscription and everything is fine. I don't know how it works.
