### ISSUE TITLE
It seems to download the same 1st video fo the course over and over again

### ISSUE THREAD

**Issue by Hikandy** [debakarr/kodekloud-downloader#3]
When I try to download any course (FREE or PREMIUM), it just downloads the same video over and over again ever though it renames it as if they all are correctly downloaded, I have provided all the cookies correctly
![image](https://user-images.githubusercontent.com/86432041/233772262-5125ede8-a24c-40b6-b0e9-ba00befd924a.png)

**Comment by debakarr** [comment]
Fixed it in 0.0.5. The way to supply cookie has been updated. Also if you don't have purchased the course it will download the same video for all the lessons.

**Comment by Hikandy** [comment]
I am using 0.0.5 and provided the cookies, the course in that pic is actually free, its not a paid course and yet i could only download the same videos
![image](https://user-images.githubusercontent.com/86432041/233785480-1814b1e8-b621-4c48-82ea-a2db91c61c8b.png)

**Comment by debakarr** [comment]
try downloading new cookie.

I tried from my end: `kodekloud dl -o . -c cookie.txt` -> selected 14.

This is the output: You can see file size are different in my case:
![image](https://user-images.githubusercontent.com/17507690/233786268-43cc4b21-8da5-4b0a-88c1-766519fcad0c.png)

You can also try enrolling in the course and hen download try downloading it.
There is also a colab book link in readme which can be used.

**Comment by Tisona** [comment]
I confirm that download without enrolling the course leads to weird results: same intro video been saved under different names.
After enrolling everything works smooth.

**Comment by Hikandy** [comment]
True, getting a new set of cookies after enrolling into the course fixes the issue
