### ISSUE TITLE
Fragment Not Found Error

### ISSUE THREAD

**Issue by iamfaseeh** [debakarr/kodekloud-downloader#37]
While downloading single course, found this error occurring in some of the files.

`[download] Got error: timed out  at  552.53KiB/s ETA 00:01 (frag 122/124)ERROR:
[download] fragment not found; Skipping fragment 56 ...
[download] Got error: timed out
[download] fragment not found; Skipping fragment 97 ...`

Here is the screenshot of the issue.

[https://ibb.co/yFyqTcF](url)

**Comment by debakarr** [comment]
Hi this generally happens because of slow internet connection. It is a known warning from yt-dlp.
