### ISSUE TITLE
videos at page 2 not scraped or downloaded

### ISSUE THREAD

**Issue by HamadaRh** [debakarr/kodekloud-downloader#39]
IF there two pages of content at section
it only get the content and videos from the first one Only
https://prnt.sc/2uyUOEUYNDkJ

all thing and videos at page 2 not scraped or downloaded

Thanks for you

**Comment by vulh0905** [comment]
I have also encountered a similar error. Please update to the new version.

**Comment by debakarr** [comment]
Closing stale issues.
Please raise a new issue if you still see the problem :)
