### ISSUE TITLE
Course resources are not downloading

### ISSUE THREAD

**Issue by Tanis74** [debakarr/kodekloud-downloader#40]
Requires a premium subscription to download course resources, even though I have one.
[4 - Course Resources.md](https://github.com/debakarr/kodekloud-downloader/files/12835426/4.-.Course.Resources.md)

**Comment by amitsat27** [comment]
Same things .vtt files are being downloaded instead of mp4.

**Comment by debakarr** [comment]
Closing stale issues.
Please raise a new issue if you still see the problem :)
