### ISSUE TITLE
Error: No such command 'dl-quiz'

### ISSUE THREAD

**Issue by nowusman** [debakarr/kodekloud-downloader#43]
Hi,

When I am trying to download quizzes using command "kodekloud dl-quiz -o KodeKloudQuiz"; I am getting Error: No such command 'dl-quiz'. Any clue on how to get around this error?

Thanks

**Comment by debakarr** [comment]
This should be fixed in the latest version. Update usign: `pip install -U kodekloud-downloader`

**Comment by debakarr** [comment]
closing this now :)
