### ISSUE TITLE
Chaos Engineering Courses

### ISSUE THREAD

**Issue by ArturiaPendragon** [debakarr/kodekloud-downloader#54]
Hello, i can't find this courses "Chaos Engineering" in the list.

**Comment by debakarr** [comment]
I can see Chaos Engineering in 31 in the list.

Another way to download course would be to use the course link like this:

```console
kodekloud dl https://learn.kodekloud.com/user/courses/chaos-engineering -o . -c cookies.txt
```

**Comment by ArturiaPendragon** [comment]
My bad :)
