### ISSUE TITLE
colab - upload cookie cell not working 

### ISSUE THREAD

**Issue by Sheldonlk** [debakarr/kodekloud-downloader#6]
Earlier, it doesn't load the courses list.

https://postimg.cc/qhwBCYFG

Now, the cookie upload box no longer appears on the "upload cookie" cell.

https://postimg.cc/563GWJCg

**Comment by debakarr** [comment]
For me it works fine. You can retry once.

**Comment by debakarr** [comment]
Closing this as issue not reproducible
