### ISSUE TITLE
'kodekloud' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by j4v3l** [debakarr/kodekloud-downloader#8]
Unable to run the downloader, I am also having the same issue on Linux. Python and Pip are in the path (no issues) I restarted and removed and reinstalled the pip package, any ideas?

**Comment by debakarr** [comment]
Can you try doing `python -m kodekloud`

**Comment by j4v3l** [comment]
> Can you try doing `python -m kodekloud`

"C:\Program Files\Python311\python.exe: No module named kodekloud"  same for Linux.

**Comment by debakarr** [comment]
Maybe first try python -m pip install kodekloud-downloader

**Comment by j4v3l** [comment]
> Maybe first try python -m pip install kodekloud-downloader

I figured it out, for whatever reason the PATH is not being read from .zshrc, so I'm using bash (.bashrc) instead.
