### ISSUE TITLE
Missing videos with javascript disabled

### ISSUE THREAD

**Issue by Tisona** [debakarr/kodekloud-downloader#9]
It turned out that Kodekloud renders totally different pages with and without javascript enabled. This applies not only to layout and css properties, but content too. Lists of videos are not the same. I discovered that trying to understand why there is one video on the site that was not downloaded.

Example: https://kodekloud.com/courses/certified-kubernetes-administrator-cka/
_Docker-vs-ContainerD (13:05)_ topic is there with JS enabled and missing with JS disabled.

Now, this downloader does not use selenium and operates pages with JS disabled. That means that there could be another missing videos in your download collection. I'm not sure if it could be fixed, not without totally rewriting scrapping part. Just letting you know.

**Comment by eniott** [comment]
I had the same issue in Linux Professional Institute LPIC1 Exam 101 course, it was missing the "Create and Change Hard Links" lesson under "Devices Linux Filesystems Filesystem Hierarchy Standard". I installed this extension https://chrome.google.com/webstore/detail/video-downloader-professi/elicpjhcidhpjomhibiffojpinpmmpil and was able to download the missing video and subtitle as well.

**Comment by debakarr** [comment]
> Devices Linux Filesystems

For me it works. Though I am using colab. These are the videos it downloaded:
```console
5 - Devices Linux Filesystems Filesystem Hierarchy Standard
        1 - Create Partitions and Filesystems � Manage MBR and GPT partition tables 1517.en.vtt (18.23 KB)
        1 - Create Partitions and Filesystems � Manage MBR and GPT partition tables 1517.mkv (87.90 MB, 0:15:17)
        2 - Create Partitions and Filesystems � Use various mkfs commands to create various filesystems 1144.en.vtt (10.85 KB)
        2 - Create Partitions and Filesystems � Use various mkfs commands to create various filesystems 1144.mkv (72.80 MB, 0:11:44)
        3 - Create Partitions and Filesystems � btrfs 0640.en.vtt (7.84 KB)
        3 - Create Partitions and Filesystems � btrfs 0640.mkv (34.02 MB, 0:06:40)
        5 - Control Mounting and Unmounting of Filesystems Part 1 � Mount at boot 1012.en.vtt (12.76 KB)
        5 - Control Mounting and Unmounting of Filesystems Part 1 � Mount at boot 1012.mkv (69.95 MB, 0:10:12)
        6 - Control Mounting and Unmounting of Filesystems Part 1 � Mount on demand 0929.en.vtt (11.34 KB)
        6 - Control Mounting and Unmounting of Filesystems Part 1 � Mount on demand 0929.mkv (58.45 MB, 0:09:29)
        7 - Control Mounting and Unmounting of Filesystems Part 2 0630.en.vtt (7.98 KB)
        7 - Control Mounting and Unmounting of Filesystems Part 2 0630.mkv (32.03 MB, 0:06:30)
        9 - Manage File Permissions and Ownership 1836.en.vtt (19.40 KB)
        9 - Manage File Permissions and Ownership 1836.mkv (100.13 MB, 0:18:36)
        11 - Create and Change Hard Links 0804.en.vtt (9.08 KB)
        11 - Create and Change Hard Links 0804.mkv (48.94 MB, 0:08:04)
        12 - Create and Change Soft Links 0432.en.vtt (5.25 KB)
        12 - Create and Change Soft Links 0432.mkv (24.86 MB, 0:04:32)
        14 - Find System Files and Place Files in the Correct Location Part 1 � FHS 0543.en.vtt (6.96 KB)
        14 - Find System Files and Place Files in the Correct Location Part 1 � FHS 0543.mkv (38.06 MB, 0:05:43)
```

**Comment by debakarr** [comment]
Closing stale issues.
